% Active Noise Control: LMS, RLS, and Kalman Filter Comparison
% Based on: "The Kalman Filter in Active Noise Control" by Lopes & Piedade

clear; clc; close all;

%% 1. System Initialization
iterations = 6000;
filter_length = 32; % 32-taps FIR filter 

% Generate Secondary Path s(n) and Unknown Primary Path w(n)
s = fir1(filter_length - 1, 0.4)'; % 32-tap low pass FIR filter [cite: 187]
w_true = fir1(filter_length - 1, 0.5)'; % 32-tap low pass FIR filter [cite: 187]

% Reference signal u(n)
% Generated by passing white noise through a filter [cite: 190]
u = filter(fir1(15, [0.2 0.8]), 1, randn(iterations, 1)); 

% Measurement noise r(n) with amplitude 0.1 [cite: 189]
r = 0.1 * randn(iterations, 1);

% Primary noise d(n)
d = filter(w_true, 1, u) + r;

%% 2. Algorithm Parameters
% LMS Parameters [cite: 28, 30]
m_LMS = 0.01; % Step size m
w_LMS = zeros(filter_length, 1);
e_LMS_history = zeros(iterations, 1);
misalign_LMS = zeros(iterations, 1);

% RLS Parameters [cite: 34-42]
lambda_RLS = 0.999;
delta = 0.01; 
P_RLS = (1/delta) * eye(filter_length); % Initialized to (1/d)*I [cite: 42]
w_RLS = zeros(filter_length, 1);
e_RLS_history = zeros(iterations, 1);
misalign_RLS = zeros(iterations, 1);

% Kalman Parameters [cite: 60-68, 156, 163-167]
lambda_Kalman = 0.99999; % Used for transition matrix [cite: 426]
J_min = var(r); % Power of r(n) [cite: 167]
Q1 = (1 - lambda_Kalman) * eye(filter_length); % State noise variance [cite: 156, 165]
Q2 = J_min; % Measurement noise variance [cite: 156]
F = eye(filter_length); % Transition matrix F(n+1,n) = I (or lambda*I) [cite: 156]

K_kalman_cov = eye(filter_length); % K(0) = E[x(0)x^H(0)] [cite: 68]
x_kalman = zeros(filter_length, 1); % state vector estimate \hat{w} [cite: 156]
e_Kalman_history = zeros(iterations, 1);
misalign_Kalman = zeros(iterations, 1);

% Buffer for the reference signal u(n)
u_buffer = zeros(filter_length, 1);

%% 3. Main Adaptive Loop
for n = 1:iterations
    % Shift buffer
    u_buffer = [u(n); u_buffer(1:end-1)];
    
    % Desired signal at current instant
    d_n = d(n);

    %% --- LMS Algorithm [cite: 26-29] ---
    y_LMS = w_LMS' * u_buffer;
    e_LMS = d_n - y_LMS;
    w_LMS = w_LMS + m_LMS * u_buffer * e_LMS; % w(n+1) = w(n) + m*u(n)*e(n)
    
    e_LMS_history(n) = e_LMS;
    misalign_LMS(n) = norm(w_LMS - w_true)^2 / norm(w_true)^2; % Eq 17 

    %% --- RLS Algorithm  ---
    y_RLS = w_RLS' * u_buffer;
    a_RLS = d_n - y_RLS; 
    
    p_RLS = P_RLS * u_buffer;
    k_denom = lambda_RLS + u_buffer' * p_RLS; 
    k_RLS = p_RLS / k_denom; % Kalman gain equivalent for RLS
    
    w_RLS = w_RLS + k_RLS * a_RLS;
    P_RLS = (1/lambda_RLS) * (P_RLS - k_RLS * u_buffer' * P_RLS);
    
    e_RLS_history(n) = a_RLS;
    misalign_RLS(n) = norm(w_RLS - w_true)^2 / norm(w_true)^2; % Eq 17 

    %% --- Kalman Algorithm [cite: 60-66, 156] ---
    % C(n) is u^T(n) [cite: 156]
    C_n = u_buffer';
    
    % Kalman Gain G(n) [cite: 60]
    % G(n) = F * K * C^H / [C * K * C^H + Q2]
    denominator = C_n * K_kalman_cov * C_n' + Q2;
    G_n = (F * K_kalman_cov * C_n') / denominator;
    
    % A priori error a(n) [cite: 61]
    a_Kalman = d_n - C_n * x_kalman;
    
    % State estimate update [cite: 62]
    x_kalman = F * x_kalman + G_n * a_Kalman;
    
    % Error covariance update K(n) & K(n+1,n) [cite: 65, 66]
    K_n = K_kalman_cov - G_n * C_n * K_kalman_cov;
    K_kalman_cov = F * K_n * F' + Q1;
    
    e_Kalman_history(n) = a_Kalman;
    misalign_Kalman(n) = norm(x_kalman - w_true)^2 / norm(w_true)^2; % Eq 17 
end

%% 4. Plotting Results
% Smoothing the squared error using a moving average filter 
window_size = 100;
smooth_LMS = 10*log10(movmean(e_LMS_history.^2, window_size));
smooth_RLS = 10*log10(movmean(e_RLS_history.^2, window_size));
smooth_Kalman = 10*log10(movmean(e_Kalman_history.^2, window_size));

figure;
subplot(2,1,1);
plot(smooth_LMS, 'DisplayName', 'LMS', 'LineWidth', 1.2); hold on;
plot(smooth_RLS, 'DisplayName', 'RLS', 'LineWidth', 1.2);
plot(smooth_Kalman, 'DisplayName', 'Kalman', 'LineWidth', 1.2);
title('Noise Level (dB) - Convergence');
xlabel('Iterations'); ylabel('Noise Level (dB)');
legend; grid on;

subplot(2,1,2);
plot(misalign_LMS, 'DisplayName', 'LMS', 'LineWidth', 1.2); hold on;
plot(misalign_RLS, 'DisplayName', 'RLS', 'LineWidth', 1.2);
plot(misalign_Kalman, 'DisplayName', 'Kalman', 'LineWidth', 1.2);
title('Normalized Misalignment');
xlabel('Iterations'); ylabel('Misalignment');
legend; grid on;

%% 5. Print Performance Metrics
clc;
% Define the tail length for calculating steady-state averages
tail_len = 1000;

% 1. Steady-State Noise Reduction (Average of last 'tail_len' iterations)
ss_noise_LMS = mean(smooth_LMS(end-tail_len:end));
ss_noise_RLS = mean(smooth_RLS(end-tail_len:end));
ss_noise_Kalman = mean(smooth_Kalman(end-tail_len:end));

% 2. Steady-State Normalized Misalignment (Average of last 'tail_len' iterations)
ss_misalign_LMS = mean(misalign_LMS(end-tail_len:end));
ss_misalign_RLS = mean(misalign_RLS(end-tail_len:end));
ss_misalign_Kalman = mean(misalign_Kalman(end-tail_len:end));

% 3. Convergence Speed (Iterations to reach -15 dB)
thresh = -15;
conv_LMS = find(smooth_LMS < thresh, 1);
if isempty(conv_LMS), conv_LMS = NaN; end % Handle case if it never reaches

conv_RLS = find(smooth_RLS < thresh, 1);
if isempty(conv_RLS), conv_RLS = NaN; end

conv_Kalman = find(smooth_Kalman < thresh, 1);
if isempty(conv_Kalman), conv_Kalman = NaN; end

% --- Print the Results to Command Window ---
fprintf('====================================================\n');
fprintf('      ACTIVE NOISE CONTROL PERFORMANCE METRICS      \n');
fprintf('====================================================\n\n');

fprintf('1. STEADY-STATE NOISE LEVEL (Target ~ -20 dB)\n');
fprintf('----------------------------------------------------\n');
fprintf('   LMS:    %7.2f dB\n', ss_noise_LMS);
fprintf('   RLS:    %7.2f dB\n', ss_noise_RLS);
fprintf('   Kalman: %7.2f dB\n\n', ss_noise_Kalman);

fprintf('2. STEADY-STATE NORMALIZED MISALIGNMENT (Closer to 0 is better)\n');
fprintf('----------------------------------------------------\n');
fprintf('   LMS:    %7.4f\n', ss_misalign_LMS);
fprintf('   RLS:    %7.4f\n', ss_misalign_RLS);
fprintf('   Kalman: %7.4f\n\n', ss_misalign_Kalman);

fprintf('3. CONVERGENCE SPEED (Iterations to cross %d dB)\n', thresh);
fprintf('----------------------------------------------------\n');
fprintf('   LMS:    %7d iterations\n', conv_LMS);
fprintf('   RLS:    %7d iterations\n', conv_RLS);
fprintf('   Kalman: %7d iterations\n\n', conv_Kalman);